name: Deploy React App to Cloud Run

on:
  push:
    branches:
      - main   # Deploy on every push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy react-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
